CREATE TABLE henkilo (
	henk_id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	etunimi VARCHAR(255) NOT NULL,
	sukunimi VARCHAR(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
